{{- if (not .Values.zitadel.configmapConfig.ExternalDomain )}}
{{- fail ".Values.zitadel.configmapConfig.ExternalDomain is mandatory"}}
{{- end }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: zitadel-config-yaml
data:
  zitadel-config-yaml: |-
    {{ .Values.zitadel.configmapConfig | toYaml | nindent 4 }}
