name: 'Test Charts'

on: 'pull_request'

jobs:
  test:

    strategy:
      matrix:
        # digests should be appended in image versions according to the KIND release notes
        # https://github.com/kubernetes-sigs/kind/releases/tag/v0.14.0
        kindest-image-tag:
          - 'v1.16.15'
          - 'v1.17.17'
          - 'v1.18.20@sha256:738cdc23ed4be6cc0b7ea277a2ebcc454c8373d7d8fb991a7fcdbd126188e6d7'
          - 'v1.19.16@sha256:d9c819e8668de8d5030708e484a9fdff44d95ec4675d136ef0a0a584e587f65c'
          - 'v1.20.15@sha256:6f2d011dffe182bad80b85f6c00e8ca9d86b5b8922cdf433d53575c4c5212248'
          - 'v1.21.12@sha256:f316b33dd88f8196379f38feb80545ef3ed44d9197dca1bfd48bcb1583210207'
          - 'v1.22.9@sha256:8135260b959dfe320206eb36b3aeda9cffcb262f4b44cda6b33f7bb73f453105'
          - 'v1.23.6@sha256:b1fa224cc6c7ff32455e0b1fd9cbfd3d3bc87ecaa8fcb06961ed1afb3db0f9ae'
          - 'v1.24.0@sha256:0866296e693efe1fed79d5e6c7af8df71fc73ae45e3679af05342239cdc5bc8e'

    runs-on: 'ubuntu-20.04'

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - id: 'checkout'
      uses: 'actions/checkout@v3'
      with:
        fetch-depth: 0

    - id: 'set-up-helm'
      uses: 'azure/setup-helm@v1'
      with:
        version: 'v3.8.1'

    - id: 'set-up-python'
      uses: 'actions/setup-python@v2'
      with:
        python-version: 3.7

    - id: 'set-up-chart-testing'
      uses: 'helm/chart-testing-action@v2.2.1'
      with:
        version: 'v3.6.0'

    - id: 'list-changed'
      run: |
        changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
        if [[ -n "$changed" ]]; then
          echo "::set-output name=changed::true"
        fi

    - id: 'add-cockroachdb-repo'
      run: 'helm repo add cockroachdb https://charts.cockroachdb.com/'
      if: steps.list-changed.outputs.changed == 'true'

    - id: 'lint'
      run: 'ct lint --target-branch ${{ github.event.repository.default_branch }}'
      if: steps.list-changed.outputs.changed == 'true'

    - name: 'create-kind'
      uses: 'helm/kind-action@v1.2.0'
      if: steps.list-changed.outputs.changed == 'true'
      with:
        node_image: 'kindest/node:${{ matrix.kindest-image-tag }}'
        version: 'v0.14.0'

    - name: 'test'
      run: 'go test -tags integration ./...'
      if: steps.list-changed.outputs.changed == 'true'
